name: CI
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm
        
      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - run: npm run lint

      - run: npm run build
